
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mydb

quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=true

mp.openapi.extensions.smallrye.info.title=Enterprise Chat API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Dokumentasi API Sistem Chat Tanpa Delete
quarkus.swagger-ui.always-include=true
quarkus.websockets-next.origins=http://localhost:3000,http://localhost:5173
quarkus.websocket.ext.path=/ws-chat

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,content-type,authorization